### ISSUE TITLE
Schedule頁面FC, reproduce rate 100%

### ISSUE THREAD

**Issue by 29988122** [CCIP-App/CCIP-Android#32]
有傳system crash log過去，想說還是來這邊寫一下比較正式
你那邊應該可以看到system environment

Steps to reproduce:
1.全新安裝
2.打開程式進schedule頁面
3.點選書籤按鈕開始加入g0v三日最愛議程
4.完整關閉程式
5.重開，進入程式schedule頁面，點選右上角書籤標記(filter)
6.FC

Expected results:
不會當掉，正常的顯示第一天的議程

Possible workaround:
在5.之後，先將議程切到第二天，再點選右上角書籤標記(filter)
這樣就能在三日議程自由切換，不會FC

能不能在其他機器上重現：未知，我沒有其他機器..lol

**Comment by Haraguroicha** [comment]
剛剛在 ZenPhone 3 5.5" 實驗證實真的 100% reproduce

**Comment by james58899** [comment]
Fixed in #34
