### ISSUE TITLE
直接顯示當天的議程

### ISSUE THREAD

**Issue by ALiangLiang** [CCIP-App/CCIP-Android#43]
Feature request

目前當使用者點進「議程」，會顯示所有議程的第一天，建議假如當天是第二天、第三天……，可以直接就顯示當天的議程，操作上也比較直覺。
![](https://i.imgur.com/XjMunRT.png)

**Comment by Haraguroicha** [comment]
@ALiangLiang @DennyHuang 你當初不願面對的問題被開票了😂
