### ISSUE TITLE
Highlight date of schdule

### ISSUE THREAD

**Issue by kcwu** [CCIP-App/CCIP-Android#49]
In this screenshot, "08/17" is selected and there is a light purple line below the date to highlight it.

The light purple line is too thin and almost invisible. It's hard for users to know which date is selected.
![image](https://user-images.githubusercontent.com/175566/63431100-b2efd280-c450-11e9-9ea5-ff35b62ab338.png)

**Comment by denny0223** [comment]
Already change the text color in f3ba40a5bb5e8bb3f17b9581e0806dff1c33b11a.
