### ISSUE TITLE
Unable to bookmark session without detail description

### ISSUE THREAD

**Issue by kcwu** [CCIP-App/CCIP-Android#50]
I'm not sure this is bug of OPass or configuration error.
On the schedule table of HITCON CMT this week, some sessions have only title and no detail description. These sessions are not bookmarkable.

**Comment by denny0223** [comment]
It's feature.

If there's no description in the session, the item is not clickable & bookmarkable, it's used for break time or lunch time. 
https://github.com/CCIP-App/CCIP-Android/blob/5da1388523c2b9d460554b35c687fb821aac2cc7/app/src/main/java/app/opass/ccip/adapter/ScheduleAdapter.kt#L63

Please close the issue, if no more suggestion, thanks.
