### ISSUE TITLE
No Response Content validation

### ISSUE THREAD

**Issue by amazuerar** [CCIP-App/CCIP-Android#57]
Dear Developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within Android apps. As result of this we identified some code locations that might have network related problems.

In this case, we address the code locations that are related to a potential issue concerning a missing validation of the response content against expected values. In order to check whether external server’s responses are correct, use validation rules. In this particular case it would be a good practice to validate in a certain moment the body of the response: `response.body()`.

In order to address this issue we recommend you to visit:

1. https://square.github.io/retrofit/2.x/retrofit/retrofit2/Response.html#body--
2. https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/

**Potential Code Location missing Response Content validation**

https://github.com/CCIP-App/CCIP-Android/blob/0fe55cd1416a7e5cf184828db07ede4874fa00a2/app/src/main/java/app/opass/ccip/extension/AsyncCall.kt#L17-L19

https://github.com/CCIP-App/CCIP-Android/blob/0fe55cd1416a7e5cf184828db07ede4874fa00a2/app/src/main/java/app/opass/ccip/extension/AsyncCall.kt#L27-L29

**Comment by coin3x** [comment]
GSON parse 失敗就會 throw exception 了
啊我們網路請求的地方都有 try catch :p
