### ISSUE TITLE
沒有正確的提示會眾使用 email 連結認證

### ISSUE THREAD

**Issue by rschiang** [CCIP-App/CCIP-Android#7]
安裝完 App 之後會出現 unknown token 的 toast，然後主畫面就會一片空白。(・ω・)

覺得有兩種可能的 blank state 設計方向：

（一）假設下載的人大多不是會眾：應該要出現「下次報名請早」或是「請贊助」的連結。（欸）
（二）假設下載的人大多是會眾：應該要出現提示，請他使用 email 裡面附的連結啟用報到功能。

**Comment by William-Tsai** [comment]
What I see is that it ask you to open with the link or scan the KKTIX QRCode. Something mistaken here?

**Comment by rschiang** [comment]
s/unknown token/invalid token/

剛剛清除資料重試了一下，看到全全你說的提示訊息了；可是我還是覺得 Invalid token 那個 toast 在從 launcher 點進去的時候可以隱藏起來。

另外提示的字有點小，或許可以參照 Material Design Guidelines 放大字級？(・ω・)

**Comment by William-Tsai** [comment]
@rschiang I think it's just because he hasn't implemented the UI part XD

**Comment by rschiang** [comment]
@William-Tsai 準確的詞是 “style” the UI 吧。期待這樣囉。XD

**Comment by denny0223** [comment]
歡迎 PR
我不想動 UI 啦~~~
