### ISSUE TITLE
Session bookmark notificaiotn need request permission on Android 13

### ISSUE THREAD

**Issue by denny0223** [CCIP-App/CCIP-Android#73]

**Comment by denny0223** [comment]
@denny0223 @CrazyFireFind 這個可以交給你處理嗎
權限檢查應該類似 b69b4f
包含我在 COSCUP 時候的修法有點暴力，這段 code 略醜，彈過去之前也沒有任何詢問
預期最近期是 8/18, 19 的 HITCON 可能會有人拿來看議程

**Comment by fdff87554** [comment]
This issue has been fixed to get Alarms&Reminders on Android 13 by PR https://github.com/CCIP-App/CCIP-Android/pull/75.
But still need Notifications Permission for both Android 13 / 14 to get right notification.
